/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#0062FF';
const tintColorDark = '#fff';

export const Colors = {
  light: {
    text: '#11181C',
    background: '#fff',
    tint: tintColorLight,
    icon: '#687076',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    primary: '#0062FF',
    secondary: '#2ecc71',
    error: '#e74c3c',
    warning: '#f39c12',
    success: '#2ecc71',
    info: '#00C8FF',
    darkC: '#000',
    transparent: 'transparent',
    blue: '#0062FF',
    red: '#D80000',
    green: '#2AC65F',
    white: '#FBFBFB',
    light: '#FFFFFF',
    lightWhite: '#FFFFFF',
    lightBlue: '#2194FF',
    lightRed: '#FF1755',
    lightGreen: '#2AFF00',
    black: '#121212',
    dark: '#3D3A45',
    gray: '#8C8896',
    lightGray: '#CACACA',
    lightBlack: '#292929',
    nagivationPrimary: '#2E2E2E',
    description: '#71727A',
    lightInput: '#F5F5F5',
    backgroundBox: '#EDEDED',
  },
  dark: {
    text: '#FBFBFB',
    background: '#121212',
    tint: tintColorDark,
    icon: '#A0A0A0',
    tabIconDefault: '#A0A0A0',
    tabIconSelected: tintColorDark,
    primary: '#0062FF',
    secondary: '#2ecc71',
    error: '#e74c3c',
    warning: '#f39c12',
    success: '#2ecc71',
    info: '#00C8FF',
    darkC: '#FBFBFB',
    transparent: 'transparent',
    blue: '#0062FF',
    red: '#D80000',
    green: '#2AC65F',
    white: '#121212',
    light: '#FFFFFF',
    lightWhite: '#1E1E1E',
    lightBlue: '#1A2A40',
    lightRed: '#3F2222',
    lightGreen: '#22372F',
    black: '#FBFBFB',
    dark: '#EFEFEF',
    gray: '#AAAAAA',
    lightGray: '#3D3D3D',
    lightBlack: '#EEEEEE',
    nagivationPrimary: '#FBFBFB',
    description: '#BBBBBB',
    lightInput: '#2A2A2A',
    backgroundBox: '#2A2A2A',
  },
};
