/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

const tintColorLight = '#0062FF';
const tintColorDark = '#fff';

export const Colors = {
  light: {
    background: '#fff',
    text: '#11181C',
    transparent: 'transparent',
    primary: '#0062FF',
    secondary: '#2ecc71',
    error: '#e74c3c',
    info: '#00C8FF',
    success: '#2ecc71',
    warning: '#f39c12',
    black: '#121212',
    blue: '#0062FF',
    dark: '#3D3A45',
    darkC: '#000',
    gray: '#8C8896',
    green: '#2AC65F',
    light: '#FFFFFF',
    lightBlack: '#292929',
    lightBlue: '#2194FF',
    lightGray: '#CACACA',
    lightGreen: '#2AFF00',
    lightRed: '#FF1755',
    lightWhite: '#FFFFFF',
    lightYellow: '#C6FF7F',
    lightOrange: '#FFB366',
    lightPink: '#FFC3DD',
    lightPurple: '#C09FF8',
    orange: '#FF8C00',
    pink: '#FF69B4',
    purple: '#8A2BE2',
    red: '#D80000',
    white: '#FBFBFB',
    yellow: '#FFD700',
    backgroundBox: '#EDEDED',
    description: '#71727A',
    icon: '#687076',
    lightInput: '#F5F5F5',
    nagivationPrimary: '#2E2E2E',
    tabBarActiveBackground: '#8B5CF6',
    tabBarBackground: '#F5F5F5',
    tabBarGradientEnd: '#69E3FF',
    tabBarGradientStart: '#8B5CF6',
    tabBarInactiveBackground: '#E5E5E5',
    tabIconDefault: '#687076',
    tabIconSelected: tintColorLight,
    tint: tintColorLight,
  },
  dark: {
    background: '#121212',
    text: '#FBFBFB',
    transparent: 'transparent',
    primary: '#0062FF',
    secondary: '#2ecc71',
    error: '#e74c3c',
    info: '#00C8FF',
    success: '#2ecc71',
    warning: '#f39c12',
    black: '#FBFBFB',
    blue: '#0062FF',
    dark: '#EFEFEF',
    darkC: '#FBFBFB',
    gray: '#AAAAAA',
    green: '#2AC65F',
    light: '#FFFFFF',
    lightBlack: '#EEEEEE',
    lightBlue: '#1A2A40',
    lightGray: '#3D3D3D',
    lightGreen: '#22372F',
    lightRed: '#3F2222',
    lightWhite: '#1E1E1E',
    lightYellow: '#4D4D00',
    lightOrange: '#664400',
    lightPink: '#664A4A',
    lightPurple: '#4A2A4A',
    orange: '#CC7000',
    pink: '#CC4A8A',
    purple: '#6B1F9A',
    red: '#D80000',
    white: '#121212',
    yellow: '#CCB000',
    backgroundBox: '#2A2A2A',
    description: '#BBBBBB',
    icon: '#A0A0A0',
    lightInput: '#2A2A2A',
    nagivationPrimary: '#FBFBFB',
    tabBarActiveBackground: '#8B5CF6',
    tabBarBackground: '#1A1A1A',
    tabBarGradientEnd: '#F97316',
    tabBarGradientStart: '#8B5CF6',
    tabBarInactiveBackground: '#2A2A2A',
    tabIconDefault: '#A0A0A0',
    tabIconSelected: tintColorDark,
    tint: tintColorDark,
  },
};
